spring:
  datasource:
    url: jdbc:mariadb://localhost:3308/product_mgmt
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true